Already on 'exp2'
wandb: Currently logged in as: stevenzhou0816100. Use `wandb login --relogin` to force relogin
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
The following values were not passed to `accelerate launch` and had defaults used instead:
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/private/home/beidic/yang/transformersprofiling/src/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 14, in <module>
    import xevaluator
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 14, in <module>
    from xhuggingface import XHFLM
  File "/private/home/beidic/yang/GRIFFIN2/xhuggingface.py", line 8, in <module>
    from llama8 import get_llama_griffin, get_llama_griffin2, LlamaForCausalLM 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/llama8.py", line 19, in <module>
    from transformers.cache_utils import Cache, DynamicCache, StaticCache, SinkCache
ModuleNotFoundError: No module named 'transformers.cache_utils'
Traceback (most recent call last):
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 14, in <module>
    import xevaluator
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 14, in <module>
    from xhuggingface import XHFLM
  File "/private/home/beidic/yang/GRIFFIN2/xhuggingface.py", line 8, in <module>
    from llama8 import get_llama_griffin, get_llama_griffin2, LlamaForCausalLM 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/llama8.py", line 19, in <module>
    from transformers.cache_utils import Cache, DynamicCache, StaticCache, SinkCache
ModuleNotFoundError: No module named 'transformers.cache_utils'
Traceback (most recent call last):
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 14, in <module>
    import xevaluator
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 14, in <module>
    from xhuggingface import XHFLM
  File "/private/home/beidic/yang/GRIFFIN2/xhuggingface.py", line 8, in <module>
    from llama8 import get_llama_griffin, get_llama_griffin2, LlamaForCausalLM 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/llama8.py", line 19, in <module>
    from transformers.cache_utils import Cache, DynamicCache, StaticCache, SinkCache
ModuleNotFoundError: No module named 'transformers.cache_utils'
Traceback (most recent call last):
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 14, in <module>
    import xevaluator
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 14, in <module>
    from xhuggingface import XHFLM
  File "/private/home/beidic/yang/GRIFFIN2/xhuggingface.py", line 8, in <module>
    from llama8 import get_llama_griffin, get_llama_griffin2, LlamaForCausalLM 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/llama8.py", line 19, in <module>
Traceback (most recent call last):
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 14, in <module>
    from transformers.cache_utils import Cache, DynamicCache, StaticCache, SinkCache
ModuleNotFoundError: No module named 'transformers.cache_utils'
    import xevaluator
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 14, in <module>
    from xhuggingface import XHFLM
  File "/private/home/beidic/yang/GRIFFIN2/xhuggingface.py", line 8, in <module>
    from llama8 import get_llama_griffin, get_llama_griffin2, LlamaForCausalLM 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/llama8.py", line 19, in <module>
    from transformers.cache_utils import Cache, DynamicCache, StaticCache, SinkCache
ModuleNotFoundError: No module named 'transformers.cache_utils'
Traceback (most recent call last):
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 14, in <module>
    import xevaluator
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 14, in <module>
    from xhuggingface import XHFLM
  File "/private/home/beidic/yang/GRIFFIN2/xhuggingface.py", line 8, in <module>
    from llama8 import get_llama_griffin, get_llama_griffin2, LlamaForCausalLM 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/llama8.py", line 19, in <module>
    from transformers.cache_utils import Cache, DynamicCache, StaticCache, SinkCache
ModuleNotFoundError: No module named 'transformers.cache_utils'
Traceback (most recent call last):
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 14, in <module>
    import xevaluator
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 14, in <module>
    from xhuggingface import XHFLM
  File "/private/home/beidic/yang/GRIFFIN2/xhuggingface.py", line 8, in <module>
    from llama8 import get_llama_griffin, get_llama_griffin2, LlamaForCausalLM 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/llama8.py", line 19, in <module>
    from transformers.cache_utils import Cache, DynamicCache, StaticCache, SinkCache
ModuleNotFoundError: No module named 'transformers.cache_utils'
Traceback (most recent call last):
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 14, in <module>
    import xevaluator
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 14, in <module>
    from xhuggingface import XHFLM
  File "/private/home/beidic/yang/GRIFFIN2/xhuggingface.py", line 8, in <module>
    from llama8 import get_llama_griffin, get_llama_griffin2, LlamaForCausalLM 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/llama8.py", line 19, in <module>
    from transformers.cache_utils import Cache, DynamicCache, StaticCache, SinkCache
ModuleNotFoundError: No module named 'transformers.cache_utils'
[2024-05-31 03:27:00,799] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1382833) of binary: /private/home/beidic/.conda/envs/griffin/bin/python
Traceback (most recent call last):
  File "/private/home/beidic/.conda/envs/griffin/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/accelerate/commands/launch.py", line 985, in launch_command
    multi_gpu_launcher(args)
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-31_03:27:00
  host      : learnfair5272.h2.fair
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1382834)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-05-31_03:27:00
  host      : learnfair5272.h2.fair
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1382835)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-05-31_03:27:00
  host      : learnfair5272.h2.fair
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1382836)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-05-31_03:27:00
  host      : learnfair5272.h2.fair
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 1382837)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-05-31_03:27:00
  host      : learnfair5272.h2.fair
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 1382838)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-05-31_03:27:00
  host      : learnfair5272.h2.fair
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 1382839)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-05-31_03:27:00
  host      : learnfair5272.h2.fair
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 1382840)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-31_03:27:00
  host      : learnfair5272.h2.fair
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1382833)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
