From github.com:Infini-AI-Lab/GRIFFIN2
   e7d7956..6b9b553  main       -> origin/main
wandb: Currently logged in as: stevenzhou0816100. Use `wandb login --relogin` to force relogin
The following values were not passed to `accelerate launch` and had defaults used instead:
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2024-05-20:12:53:05,588 INFO     [main.py:288] Verbosity set to INFO
2024-05-20:12:53:05,588 INFO     [main.py:288] Verbosity set to INFO
2024-05-20:12:53:06,028 INFO     [main.py:288] Verbosity set to INFO
2024-05-20:12:53:06,081 INFO     [main.py:288] Verbosity set to INFO
2024-05-20:12:53:06,161 INFO     [main.py:288] Verbosity set to INFO
2024-05-20:12:53:06,177 INFO     [main.py:288] Verbosity set to INFO
2024-05-20:12:53:06,178 INFO     [main.py:288] Verbosity set to INFO
2024-05-20:12:53:06,192 INFO     [main.py:288] Verbosity set to INFO
2024-05-20:12:53:12,650 INFO     [main.py:378] Selected Tasks: ['gsm8k', 'ifeval', 'triviaqa']
2024-05-20:12:53:12,650 INFO     [main.py:378] Selected Tasks: ['gsm8k', 'ifeval', 'triviaqa']
2024-05-20:12:53:12,654 INFO     [main.py:378] Selected Tasks: ['gsm8k', 'ifeval', 'triviaqa']
2024-05-20:12:53:12,657 INFO     [main.py:378] Selected Tasks: ['gsm8k', 'ifeval', 'triviaqa']
2024-05-20:12:53:12,660 INFO     [xevaluator.py:137] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234
2024-05-20:12:53:12,660 INFO     [xevaluator.py:137] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234
2024-05-20:12:53:12,660 INFO     [xevaluator.py:187] Initializing xhf model, with arguments: {'pretrained': 'meta-llama/Llama-2-7b-chat-hf', 'griffin': False, 'check': False, 'griffinnotcats': False}
2024-05-20:12:53:12,660 INFO     [xevaluator.py:137] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234
2024-05-20:12:53:12,660 INFO     [xevaluator.py:187] Initializing xhf model, with arguments: {'pretrained': 'meta-llama/Llama-2-7b-chat-hf', 'griffin': False, 'check': False, 'griffinnotcats': False}
2024-05-20:12:53:12,660 INFO     [xevaluator.py:187] Initializing xhf model, with arguments: {'pretrained': 'meta-llama/Llama-2-7b-chat-hf', 'griffin': False, 'check': False, 'griffinnotcats': False}
2024-05-20:12:53:12,662 INFO     [xevaluator.py:137] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234
2024-05-20:12:53:12,662 INFO     [xevaluator.py:187] Initializing xhf model, with arguments: {'pretrained': 'meta-llama/Llama-2-7b-chat-hf', 'griffin': False, 'check': False, 'griffinnotcats': False}
2024-05-20:12:53:12,663 INFO     [main.py:378] Selected Tasks: ['gsm8k', 'ifeval', 'triviaqa']
2024-05-20:12:53:12,668 INFO     [xevaluator.py:137] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234
2024-05-20:12:53:12,668 INFO     [xevaluator.py:187] Initializing xhf model, with arguments: {'pretrained': 'meta-llama/Llama-2-7b-chat-hf', 'griffin': False, 'check': False, 'griffinnotcats': False}
2024-05-20:12:53:12,724 INFO     [main.py:378] Selected Tasks: ['gsm8k', 'ifeval', 'triviaqa']
2024-05-20:12:53:12,729 INFO     [xevaluator.py:137] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234
2024-05-20:12:53:12,729 INFO     [xevaluator.py:187] Initializing xhf model, with arguments: {'pretrained': 'meta-llama/Llama-2-7b-chat-hf', 'griffin': False, 'check': False, 'griffinnotcats': False}
2024-05-20:12:53:12,830 INFO     [main.py:378] Selected Tasks: ['gsm8k', 'ifeval', 'triviaqa']
2024-05-20:12:53:12,834 INFO     [xevaluator.py:137] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234
2024-05-20:12:53:12,834 INFO     [xevaluator.py:187] Initializing xhf model, with arguments: {'pretrained': 'meta-llama/Llama-2-7b-chat-hf', 'griffin': False, 'check': False, 'griffinnotcats': False}
2024-05-20:12:53:13,166 INFO     [main.py:378] Selected Tasks: ['gsm8k', 'ifeval', 'triviaqa']
2024-05-20:12:53:13,170 INFO     [xevaluator.py:137] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234
2024-05-20:12:53:13,170 INFO     [xevaluator.py:187] Initializing xhf model, with arguments: {'pretrained': 'meta-llama/Llama-2-7b-chat-hf', 'griffin': False, 'check': False, 'griffinnotcats': False}
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 1/2 [01:19<01:19, 79.60s/it]Loading checkpoint shards:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 1/2 [01:21<01:21, 81.41s/it]Loading checkpoint shards:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 1/2 [01:21<01:21, 81.50s/it]Loading checkpoint shards:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 1/2 [01:21<01:21, 81.52s/it]Loading checkpoint shards:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 1/2 [01:22<01:22, 82.08s/it]Loading checkpoint shards:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 1/2 [01:21<01:21, 81.44s/it]Loading checkpoint shards:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 1/2 [01:21<01:21, 81.47s/it]Loading checkpoint shards:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 1/2 [01:21<01:21, 81.51s/it]Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 48.36s/it]Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 53.04s/it]
Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 48.43s/it]Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 53.39s/it]
Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 48.48s/it]Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 53.43s/it]
Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 48.44s/it]Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 53.39s/it]
Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 48.48s/it]Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 53.42s/it]
Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 48.47s/it]Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 53.42s/it]
Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 48.47s/it]Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:46<00:00, 53.42s/it]
Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:47<00:00, 48.75s/it]Loading checkpoint shards: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [01:47<00:00, 53.75s/it]
2024-05-20:12:55:01,623 INFO     [xhuggingface.py:314] Using 8 devices with data parallelism
[nltk_data] Downloading package punkt to
[nltk_data]     /private/home/beidic/nltk_data...
[nltk_data] Downloading package punkt to
[nltk_data]     /private/home/beidic/nltk_data...
Traceback (most recent call last):
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions_util.py", line 28, in download_nltk_resources
[nltk_data] Downloading package punkt to
[nltk_data]     /private/home/beidic/nltk_data...
    nltk.data.find("tokenizers/punkt")
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/nltk/data.py", line 583, in find
Traceback (most recent call last):
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions_util.py", line 28, in download_nltk_resources
    nltk.data.find("tokenizers/punkt")
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)    
raise LookupError(resource_not_found)
LookupError: LookupError
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt[0m

  Searched in:
    - '/private/home/beidic/nltk_data'
    - '/private/home/beidic/.conda/envs/griffin/nltk_data'
    - '/private/home/beidic/.conda/envs/griffin/share/nltk_data'
    - '/private/home/beidic/.conda/envs/griffin/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
: 

**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt[0m

  Searched in:
    - '/private/home/beidic/nltk_data'
    - '/private/home/beidic/.conda/envs/griffin/nltk_data'
    - '/private/home/beidic/.conda/envs/griffin/share/nltk_data'
    - '/private/home/beidic/.conda/envs/griffin/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:
Traceback (most recent call last):

Traceback (most recent call last):
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 465, in <module>
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 465, in <module>
    cli_evaluate()
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 384, in cli_evaluate
    cli_evaluate()
  File "/private/home/beidic/yang/GRIFFIN2/main.py", line 384, in cli_evaluate
    results = xevaluator.simple_evaluate(
              ^^^^^    ^results = xevaluator.simple_evaluate(^
^^^^^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^
   File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/utils.py", line 288, in _wrapper
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/utils.py", line 288, in _wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 221, in simple_evaluate
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/yang/GRIFFIN2/xevaluator.py", line 221, in simple_evaluate
    task_dict = get_task_dict(tasks, task_manager)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^task_dict = get_task_dict(tasks, task_manager)^
^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/__init__.py", line 420, in get_task_dict
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/__init__.py", line 420, in get_task_dict
        task_name_from_string_dict = task_manager.load_task_or_group(task_name_from_string_dict = task_manager.load_task_or_group(

                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/__init__.py", line 270, in load_task_or_group
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/__init__.py", line 270, in load_task_or_group
    collections.ChainMap(*map(self._load_individual_task_or_group, task_list))
    collections.ChainMap(*map(self._load_individual_task_or_group, task_list))
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/__init__.py", line 160, in _load_individual_task_or_group
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/__init__.py", line 160, in _load_individual_task_or_group
    task_config = self._get_config(name_or_config)
      task_config = self._get_config(name_or_config) 
                      ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/__init__.py", line 112, in _get_config
^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/__init__.py", line 112, in _get_config
    return utils.load_yaml_config(yaml_path, mode="full")
     return utils.load_yaml_config(yaml_path, mode="full") 
         ^^^^^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/utils.py", line 324, in load_yaml_config
^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/utils.py", line 324, in load_yaml_config
    yaml_config = yaml.full_load(file)
           yaml_config = yaml.full_load(file) 
           ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^
^^^^  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/__init__.py", line 105, in full_load
^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/__init__.py", line 105, in full_load
[nltk_data] Downloading package punkt to
[nltk_data]     /private/home/beidic/nltk_data...
    return load(stream, FullLoader)    
return load(stream, FullLoader)
                     ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
        return loader.get_single_data() 
      ^^^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^
^^^^  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 51, in get_single_data
^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
    return self.construct_document(node)
               ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 60, in construct_document
^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    for dummy in generator:
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^    ^value = self.construct_mapping(node)^
^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 218, in construct_mapping
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 143, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 100, in construct_object
value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/utils.py", line 308, in import_function
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/utils.py", line 308, in import_function
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/utils.py", line 4, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/utils.py", line 4, in <module>
[nltk_data] Downloading package punkt to
[nltk_data]     /private/home/beidic/nltk_data...
    from lm_eval.tasks.ifeval import instructions_registry
    from lm_eval.tasks.ifeval import instructions_registry
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions_registry.py", line 16, in <module>
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions_registry.py", line 16, in <module>
        from lm_eval.tasks.ifeval import instructionsfrom lm_eval.tasks.ifeval import instructions

  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions.py", line 26, in <module>
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions.py", line 26, in <module>
[nltk_data] Downloading package punkt to
[nltk_data]     /private/home/beidic/nltk_data...
    from lm_eval.tasks.ifeval import instructions_util
    from lm_eval.tasks.ifeval import instructions_util
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions_util.py", line 33, in <module>
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions_util.py", line 33, in <module>
    download_nltk_resources()
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions_util.py", line 30, in download_nltk_resources
    download_nltk_resources()
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/lm_eval/tasks/ifeval/instructions_util.py", line 30, in download_nltk_resources
    nltk.download("punkt")
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/nltk/downloader.py", line 777, in download
    nltk.download("punkt")
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/nltk/downloader.py", line 777, in download
    for msg in self.incr_download(info_or_id, download_dir, force):    
for msg in self.incr_download(info_or_id, download_dir, force):
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/nltk/downloader.py", line 642, in incr_download
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/nltk/downloader.py", line 642, in incr_download
    yield from self._download_package(info, download_dir, force)
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/nltk/downloader.py", line 699, in _download_package
    yield from self._download_package(info, download_dir, force)
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/nltk/downloader.py", line 701, in _download_package
    os.makedirs(download_dir)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/private/home/beidic/nltk_data'
    os.makedirs(os.path.join(download_dir, info.subdir))
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/private/home/beidic/nltk_data/tokenizers'
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data]   Unzipping tokenizers/punkt.zip.
Downloading readme:   0%|          | 0.00/28.0 [00:00<?, ?B/s]Downloading readme: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 28.0/28.0 [00:00<00:00, 321kB/s]
Downloading data:   0%|          | 0.00/207k [00:00<?, ?B/s]Downloading data: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 207k/207k [00:00<00:00, 1.10MB/s]Downloading data: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 207k/207k [00:00<00:00, 1.10MB/s]
Generating train split:   0%|          | 0/541 [00:00<?, ? examples/s]Generating train split: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 541/541 [00:00<00:00, 42903.41 examples/s]
2024-05-20:12:55:07,848 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,848 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,854 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,854 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,856 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,856 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,869 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,869 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,885 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,885 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,896 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
2024-05-20:12:55:07,897 WARNING  [task.py:322] [Task: ifeval] has_training_docs and has_validation_docs are False, using test_docs as fewshot_docs but this is not recommended.
[2024-05-20 12:55:08,925] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2716416 closing signal SIGTERM
[2024-05-20 12:55:08,926] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2716417 closing signal SIGTERM
[2024-05-20 12:55:08,926] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2716418 closing signal SIGTERM
[2024-05-20 12:55:08,926] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2716419 closing signal SIGTERM
[2024-05-20 12:55:08,926] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2716420 closing signal SIGTERM
[2024-05-20 12:55:08,926] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 2716422 closing signal SIGTERM
[2024-05-20 12:55:09,756] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 5 (pid: 2716421) of binary: /private/home/beidic/.conda/envs/griffin/bin/python
Traceback (most recent call last):
  File "/private/home/beidic/.conda/envs/griffin/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/accelerate/commands/launch.py", line 985, in launch_command
    multi_gpu_launcher(args)
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/home/beidic/.conda/envs/griffin/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-05-20_12:55:08
  host      : learnfair5063.h2.fair
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 2716423)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-20_12:55:08
  host      : learnfair5063.h2.fair
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 2716421)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
